import Vue from 'vue'
import { NavBar, Form, List, Cell, PullRefresh, CellGroup, Tab, Tabs, Field, Button, CountDown, Image as VanImage, Tabbar, TabbarItem, Grid, GridItem, Icon } from 'vant'

Vue.use(NavBar)
Vue.use(Form)
Vue.use(Field)
Vue.use(Button)
Vue.use(CountDown)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(VanImage)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Icon)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(List)
Vue.use(PullRefresh)
